package com.univpm.oop.GeneralGUI;


import java.util.ArrayList;
import java.util.Date;


import com.univpm.oop.model.Citta;
import com.univpm.oop.services.Convertitore;
import com.univpm.oop.statistiche.Tempo;
import com.univpm.oop.statistiche.Stat;

/**
* SingleCity è un frame che si occupa di valutare il meteo su singola città
* @author Diego
*/
@SuppressWarnings("serial")
public class SingleCity extends javax.swing.JFrame {
    
   /**
    * Creates new form SingleCity
    */
   public SingleCity() {
       initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   private void initComponents() {

       jLabel1 = new javax.swing.JLabel();
       MenùReturn = new javax.swing.JButton();
       jLabel2 = new javax.swing.JLabel();
       jButton1 = new javax.swing.JButton();
       jComboBox1 = new javax.swing.JComboBox<>();
       NameCity = new javax.swing.JLabel();
       MediaTemp = new javax.swing.JLabel();
       VarTemp = new javax.swing.JLabel();
       MediaHum = new javax.swing.JLabel();
       VarHum = new javax.swing.JLabel();
       MediaPres = new javax.swing.JLabel();
       VarPres = new javax.swing.JLabel();

       setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

       jLabel1.setText("Single City Meteo");

       MenùReturn.setText("Ritorna al menù");
       MenùReturn.addMouseListener(new java.awt.event.MouseAdapter() {
           public void mouseClicked(java.awt.event.MouseEvent evt) {
               MenùReturnMouseClicked(evt);
           }
       });
      

       jLabel2.setText("Seleziona la Città");

       jButton1.setText("Cerca");
       jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
           public void mousePressed(java.awt.event.MouseEvent evt) {
               jButton1MousePressed(evt);
           }
       });

       jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "L'aquila", "Potenza", "Catanzaro", "Napoli", "Bologna", "Trieste", "Roma", "Genova", "Milano", "Ancona", "Campobasso", "Torino", "Bari", "Cagliari", "Palermo", "Firenze", "Trento", "Perugia", "Aosta", "Venezia" }));
       

       MediaTemp.setText("Media Temperatura");

       VarTemp.setText("Varianza Temperatura");

       MediaHum.setText("Media Umidità");

       VarHum.setText("Varianza Umidità");

       MediaPres.setText("Media Pressione");

       VarPres.setText("Varianza Pressione");

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
               .addContainerGap(650, Short.MAX_VALUE)
               .addComponent(MenùReturn)
               .addGap(42, 42, 42))
           .addGroup(layout.createSequentialGroup()
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                   .addComponent(NameCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                   .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                       .addComponent(jLabel1)
                       .addGroup(layout.createSequentialGroup()
                           .addComponent(jLabel2)
                           .addGap(1, 1, 1)))
                   .addComponent(MediaHum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                   .addComponent(VarTemp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                   .addComponent(VarHum, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                   .addComponent(MediaTemp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                   .addComponent(VarPres, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                   .addComponent(MediaPres, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jLabel1)
               .addGap(33, 33, 33)
               .addComponent(jLabel2)
               .addGap(5, 5, 5)
               .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addComponent(jButton1)
               .addGap(11, 11, 11)
               .addComponent(NameCity, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(17, 17, 17)
               .addComponent(MediaTemp)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addComponent(VarTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(MediaHum, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(VarHum, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(MediaPres, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addComponent(VarPres, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(MenùReturn)
               .addGap(34, 34, 34))
       );

       pack();
   }// </editor-fold>                        

   /**
    * La funzione permette di ritornare al menu principale
    * @author Diego
    * @param evt
    */
   private void MenùReturnMouseClicked(java.awt.event.MouseEvent evt) {                                        
       // La funzione permette di ritornare al menu principale
       new StartingFrame().setVisible(true);
       dispose();
   }                                       

                                       

   /**
    * Ricerca il meteo di una singola città quando viene premuto il pulsante
    * @param evt
    * @return i dati ottenuti sono della media e varianza di temperatura, pressione e umidità
    */
   private void jButton1MousePressed(java.awt.event.MouseEvent evt) {                                      
       // Ricerca del meteo su singola città
	   String DataType=new String();
	   DataType= "Giornaliero";
	   String citta= (String)jComboBox1.getSelectedItem();
	  if(String.valueOf(citta)=="L'aquila"|| String.valueOf(citta)=="L'Aquila")citta="Comune di L\u0027Aquila";
	  if(String.valueOf(citta)=="Roma")citta="Rome";
	   System.out.println(citta);
	   Date[] date = Tempo.getDateFromString(DataType);
	   Stat stat = new Stat();
	   Convertitore conv = new Convertitore();
		Double[] valP ;
		Double[] valU ;
		Double[] valT ;
		ArrayList<Citta> c = conv.JsonToCitta(date[0], date[1]);
		
			 valP = stat.getValues(c, citta,0);
			 valU = stat.getValues(c, citta,1);
			 valT = stat.getValues(c, citta,2);
		
		
		double mediaP = stat.getMedia(valP);
		double mediaU = stat.getMedia(valU);
		double mediaT = stat.getMedia(valT);
		double varT=stat.getVarianza(valT);
		double varP=stat.getVarianza(valP);
		double varU=stat.getVarianza(valU);
	System.out.println(date[0] +" " +date[1]);

	   
     NameCity.setText("Meteo di " + jComboBox1.getSelectedItem());
   MediaTemp.setText("Temperatura media: " + String.valueOf((float)mediaT) +"° ");
   VarTemp.setText("Varianza della temperatura: " + String.valueOf((float)varT) +"° ");
   MediaPres.setText("Pressione media: " +String.valueOf((float)mediaP)+"Pa");
   VarPres.setText("Varianza della pressione: " +String.valueOf((float)varP)+ "Pa");
   VarHum.setText("Varianza dell'umidità: " + String.valueOf((float)varU)+"%");
   MediaHum.setText("Media dell'umidità: " +(float)mediaU+ "%");
   }                                     

                                    

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
       /* Set the Nimbus look and feel */
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
       /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        */
       try {
           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               if ("Nimbus".equals(info.getName())) {
                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
                   break;
               }
           }
       } catch (ClassNotFoundException ex) {
           java.util.logging.Logger.getLogger(SingleCity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (InstantiationException ex) {
           java.util.logging.Logger.getLogger(SingleCity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (IllegalAccessException ex) {
           java.util.logging.Logger.getLogger(SingleCity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (javax.swing.UnsupportedLookAndFeelException ex) {
           java.util.logging.Logger.getLogger(SingleCity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       }
       //</editor-fold>
       
       /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
               new SingleCity().setVisible(true);
           }
       });
   }

   // Variables declaration - do not modify     
   /**
    * Media dell'umidità
    */
   private javax.swing.JLabel MediaHum;
   /**
    * Media della pressione
    */
   private javax.swing.JLabel MediaPres;
   /**
    * Media della temperatura
    */
   private javax.swing.JLabel MediaTemp;
   /**
    * Pulsante per il ritorno al menu
    */
   private javax.swing.JButton MenùReturn;
   /**
    * NameCity
    */
   private javax.swing.JLabel NameCity;
   /**
    * Varianza dell'umidità
    */
   private javax.swing.JLabel VarHum;
   /**
    * Varianza della pressione
    */
   private javax.swing.JLabel VarPres;
   /**
    * Varianza della temperatura
    */
   private javax.swing.JLabel VarTemp;
   /**
    * Pulsante per la ricerca meteo
    */
   private javax.swing.JButton jButton1;
   /**
    * Selezione della città
    */
   private javax.swing.JComboBox<String> jComboBox1;
   /**
    * Titolo frame
    */
   private javax.swing.JLabel jLabel1;
   /**
    * Titolo selezione città
    */
   private javax.swing.JLabel jLabel2;
   // End of variables declaration                   
}
